### ISSUE TITLE
Error when attempting to run tests on the meccano dataset

### ISSUE THREAD

**Issue by divineSix** [fpv-iplab/MECCANO#1]
Missing property `num_videos` in the Meccano dataset class. 

```
Traceback (most recent call last):
  File "/ssd_scratch/cvit/vishalt/slowfast-experiments/tools/run_net.py", line 52, in <module>
    main()
  File "/ssd_scratch/cvit/vishalt/slowfast-experiments/tools/run_net.py", line 37, in main
    launch_job(cfg=cfg, init_method=args.init_method, func=test)
  File "/ssd_scratch/cvit/vishalt/slowfast-experiments/slowfast/utils/misc.py", line 430, in launch_job
    func(cfg=cfg)
  File "/ssd_scratch/cvit/vishalt/slowfast-experiments/tools/test_net.py", line 233, in test
    test_loader.dataset.num_videos
AttributeError: 'Meccano' object has no attribute 'num_videos'
```

Referencing `kinetics.py` in `build/lib/slowfast/datasets` (post slowfast build), there is a property `num_videos` defined in the Kinetics class file which is the same as the `__len__` property. Displayed in below screenshot
![image](https://user-images.githubusercontent.com/16540712/193004801-078e2fd8-84dd-4120-bb5a-97d900c7722b.png)

I have tried doing the same by directly editing the post-build meccano.py (`build/lib/slowfast/datasets` directory), but that property is not getting read. Encountering the same error. Can you please verify?

**Comment by divineSix** [comment]
The fix is the same as adding the property `num_videos` to `slowfast/datasets/meccano.py` and then rebuilding the code. 
```
@property
    def num_videos(self):
        """
        Returns:
            (int): the number of videos in the dataset.
        """
        return len(self._path_to_videos)
```

It did not work in my previous attempt because I was trying to add it directly in the build generated files.

**Comment by francescoragusa** [comment]
Hello @divineSix, 
the property "num_videos" has been introduced in a new version of Pyslowfast.
Thanks for your suggestion on how to fix it.
