### ISSUE TITLE
Error encountered when trying to test using PySlowFast ('action_id')

### ISSUE THREAD

**Issue by jkini** [fpv-iplab/MECCANO#10]
I am interested in reproducing the results from the SlowFast network, using the provided pre-trained weights.  

Error occurs in meccano.py

```python
File "/home/meccano/slowfast/slowfast/datasets/meccano.py", line 110, in _construct_loader
    self._labels.append(int(action_label))
ValueError: invalid literal for int() with base 10: 'action_id'
```

Any recommendations or fixes?

**Comment by jkini** [comment]
Updating meccano.py to skip reading the header row from the .csv file works for me.

for clip_idx, path_label in enumerate(f.read().splitlines()**[1:]**):

**Fix available:** Refer 'meccano.py' line 30 from mentioned repository https://github.com/jkini/Meccano

**Comment by francescoragusa** [comment]
Hi @jkini , help to hear that you solved the problem. Can you share your updated file? I can replace it in the repo to avoid to encounter the same error from other researchers.
Thank you very much!
