### ISSUE TITLE
Code for running the demo 

### ISSUE THREAD

**Issue by nitish11** [fpv-iplab/MECCANO#13]
I could not find proper instruction for running the demo.  I could not find any key in any of the config files also. 

Could you please guide how can we run the demo?

**Comment by francescoragusa** [comment]
Hello @nitish11 , 
can you please give me more details?
Which demo do you want to run?

Francesco

**Comment by nitish11** [comment]
@francescoragusa : 
I am trying to run demo for Action Recognition using SlowFast model, as mentioned here. 
https://github.com/facebookresearch/SlowFast/blob/main/tools/run_net.py#L46

**Comment by francescoragusa** [comment]
We did not expect to run _demo_ function with our model.
If you want to test the model, you may set in the config file:
TRAIN:
  ENABLE: False
TEST:
  ENABLE: True

 and then you can run the following command:

`python tools/run_net.py --cfg path_to_your_config_file --[optional flags]`

**Comment by nitish11** [comment]
@francescoragusa : Thanks for the suggestion. I updated the config and run the following code. 

_python tools/run_net.py --cfg configs/action_recognition/SLOWFAST_8x8_R50_MECCANO.yaml_

![image](https://github.com/fpv-iplab/MECCANO/assets/2395767/e25a31f7-81ec-4512-b012-fa47136b443c)

I was getting this error, am I using wrong version of the code?

I have added a variable in def _construct_loader(self) in meccano.py
**`self.num_videos = len(self._path_to_videos)`**

I got the issue resolved. But, I am getting another error. 
![image](https://github.com/fpv-iplab/MECCANO/assets/2395767/b9d6ad5c-a345-42e3-8b5d-12d31053dd6f)

**Comment by nitish11** [comment]
I fixed the above issue also by fixing the path, but now I am getting different error as below for some of the images. 

![image](https://github.com/fpv-iplab/MECCANO/assets/2395767/f3c12fc2-2ac6-482f-b1a0-97c86b6710cc)

Could you please help out to resolve the issue.

**Comment by francescoragusa** [comment]
In the old version of Pyslowfast, in `enumarate(testloader)` only 4 values have been expected:
`for cur_iter, (inputs, labels, video_idx, meta) in enumerate(test_loader):`

now, in the new version, the expected values are 5:

`for cur_iter, (inputs, labels, video_idx, time, meta) in enumerate(test_loader):`

You can fix this issue replacing in the `get_item` function in `meccano.py` the number of values returned:

`return frames, label, index, {}, {}`

**Comment by nitish11** [comment]
Thanks for the suggestion and guide. I am able to run the test code now.
