### ISSUE TITLE
Encoding error when trying to read the predictions. 

### ISSUE THREAD

**Issue by divineSix** [fpv-iplab/MECCANO#3]
Upon locally fixing / bypassing previously listed errors ([link](https://github.com/fpv-iplab/MECCANO/issues/2), [link](https://github.com/fpv-iplab/MECCANO/issues/1)), was able to get a successfully executed message. Unable to read the predictions output however, as it looks like the output is in binary. 

Screenshot of the success message: 
![image](https://user-images.githubusercontent.com/16540712/193058116-8876a854-a034-4973-93f2-09233082f95d.png)

Screenshot of the error when reading the file: 
![image](https://user-images.githubusercontent.com/16540712/193058282-f7772d47-f432-4721-9b58-aa042f6f28e1.png)
![image](https://user-images.githubusercontent.com/16540712/193058388-8b84201f-fd93-437a-8f77-b613bfbe58e0.png)

**Comment by francescoragusa** [comment]
The output predictions are encoded in a pickle file.
To read this file you need to use the following instruction:

`preds = pd.read_pickle(r'out_predictions')`
