### ISSUE TITLE
[RULSTM Code] Testing Mode

### ISSUE THREAD

**Issue by Victoria-Manousaki** [fpv-iplab/MECCANO#4]
Hello,

In the main.py file provided for the Meccano dataset:

1. In line [679](https://github.com/fpv-iplab/MECCANO/blob/169b023dc0b61989a8fc69dcf8c613748c88a64d/RULSTM_files/main.py#L679) the function get_meccano_scores is required to return 4 values but the [function ](https://github.com/fpv-iplab/MECCANO/blob/169b023dc0b61989a8fc69dcf8c613748c88a64d/RULSTM_files/main.py#L338)returns 3 by default.

2. Lines [685](https://github.com/fpv-iplab/MECCANO/blob/169b023dc0b61989a8fc69dcf8c613748c88a64d/RULSTM_files/main.py#L685)-[686](https://github.com/fpv-iplab/MECCANO/blob/169b023dc0b61989a8fc69dcf8c613748c88a64d/RULSTM_files/main.py#L686) raise an error because the verb_scores and noun_scores are not calculated for Meccano.

Any recommendations/fixes?

Thank you for your time,
Victoria

**Comment by francescoragusa** [comment]
Hello Victoria,

thanks for your interest about the MECCANO Dataset.
I fixed the code and I uploaded the main.py and the meccano_dataset.py files.
In the README I added also the command to run the test with RULSTM on the MECCANO Dataset.

Thanks.

**Comment by Victoria-Manousaki** [comment]
I am now able to successfully test the code.
Thank you very much for your quick response.

**Comment by nitish11** [comment]
@Victoria-Manousaki  : I an unable to run RULSTM testing code. 

Could you please help to resolve the issue.  https://github.com/fpv-iplab/MECCANO/issues/12
