### ISSUE TITLE
Cannot import name 'cat_all_gather' from 'pytorchvideo.layers.distributed' 

### ISSUE THREAD

**Issue by PB988820** [fpv-iplab/MECCANO#7]
Respected Sir,

I am using :-
Name: torch
Version: 2.0.1+cu118

Please see  the error is coming even after typing. I cant even run train.py/test.py Kindly help me to solve this problem.
    int_classes = int  
!python tools/run_net.py --cfg configs/Kinetics/C2D_8x8_R50.yaml NUM_GPUS 1 TRAIN.BATCH_SIZE 8 SOLVER.BASE_LR 0.0125 DATA.PATH_TO_DATA_DIR path_to_your_data_folder 

Traceback (most recent call last):
  File "/content/slowfast/tools/run_net.py", line 6, in <module>
    from slowfast.utils.misc import launch_job
  File "/content/slowfast/slowfast/utils/misc.py", line 19, in <module>
    import slowfast.utils.logging as logging
  File "/content/slowfast/slowfast/utils/logging.py", line 15, in <module>
    import slowfast.utils.distributed as du
  File "/content/slowfast/slowfast/utils/distributed.py", line 12, in <module>
    from pytorchvideo.layers.distributed import (  # noqa
ImportError: cannot import name 'cat_all_gather' from 'pytorchvideo.layers.distributed' (/usr/local/lib/python3.10/dist-packages/pytorchvideo/layers/distributed.py)

**Comment by PB988820** [comment]
On running
!python3 tools/run_net.py --/content/drive/MyDrive/MECCANO-master/configs/action_recognition/MECCANO_first_version/I3D_8x8_R50.yaml, the following error is coming:
Traceback (most recent call last):
  File "/content/slowfast/tools/run_net.py", line 6, in <module>
    from slowfast.utils.misc import launch_job
  File "/content/slowfast/slowfast/utils/misc.py", line 19, in <module>
    import slowfast.utils.logging as logging
  File "/content/slowfast/slowfast/utils/logging.py", line 15, in <module>
    import slowfast.utils.distributed as du
  File "/content/slowfast/slowfast/utils/distributed.py", line 12, in <module>
    from pytorchvideo.layers.distributed import (  # noqa
ImportError: cannot import name 'cat_all_gather' from 'pytorchvideo.layers.distributed' (/usr/local/lib/python3.10/dist-packages/pytorchvideo/layers/distributed.py)

**Comment by francescoragusa** [comment]
Dear @PB988820 this error comes from the pyslowfast library.
To solve this problem you could refer to the official repo of [Pyslowfast ](https://github.com/facebookresearch/SlowFast)where this kind of issues have been discussed.
In particular, this problem has been solved in this [issue ](https://github.com/facebookresearch/SlowFast/issues/636).

**Comment by francescoragusa** [comment]
@PB988820 have you any updates about this error?

**Comment by PB988820** [comment]
No sir, i didnot try after that
