### ISSUE TITLE
ModuleNotFoundError: No module named 'slowfast.models.custom_video_model_builder_extract_features

### ISSUE THREAD

**Issue by ghost** [fpv-iplab/MECCANO#8]
![image](https://github.com/fpv-iplab/MECCANO/assets/136063449/0a9ca174-4864-404c-8a6b-a1abe0356941)

According to your instructions, I placed the files "init.py" in the slowfast/models/ folder, but I encountered a problem "## ModuleNotFoundError: No module named 'slowfast.models.custom_video_model_builder_extract_features'" when I run the test.

It seems that the file “custom_video_model_builder_extract_features” never be given in project "MECCANO", could you help with this problem?

**Comment by francescoragusa** [comment]
Dear @pxhdky, 
you're right, the file custom_video_model_builder_extract_features.py does not exist.
You can remove that line of code. 
I update the init.py file.

Thank you for your contribution!
